# Generated by Django 2.2 on 2019-04-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='dimensionsapp.Author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensionsapp.Binding', verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='format_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensionsapp.FormatBook', verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='bookimage', verbose_name='Фото обложки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный (доступен для заказа)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='jenre',
            field=models.ManyToManyField(to='dimensionsapp.Jenre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensionsapp.PublishingHouse', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensionsapp.Serie', verbose_name='Серия'),
        ),
    ]
