# Generated by Django 2.2 on 2019-04-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0003_auto_20190408_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restrictions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensionsapp.AgeRestriction', verbose_name='Возрастные ограничения'),
        ),
    ]
