# Generated by Django 2.2 on 2019-04-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0005_auto_20190408_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensionsapp.Serie', verbose_name='Серия'),
        ),
    ]
