# Generated by Django 2.2 on 2019-04-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0006_auto_20190410_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensionsapp.Serie', verbose_name='Серия'),
        ),
    ]
