# Generated by Django 2.2 on 2019-04-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0007_auto_20190410_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Пункт меню')),
                ('url_name', models.CharField(max_length=100, verbose_name='Название ссылки')),
                ('parent_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_menu_item', related_query_name='parent_menu_item', to='goodsapp.MenuModel')),
            ],
        ),
    ]
