# Generated by Django 2.2 on 2019-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0009_auto_20190419_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Пункт меню'),
        ),
    ]
