# Generated by Django 2.2 on 2019-04-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0010_auto_20190419_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuModel',
            new_name='Menu',
        ),
    ]

    atomic = False
