# Generated by Django 2.2 on 2019-05-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0011_auto_20190419_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
