# Generated by Django 2.2.1 on 2019-06-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0012_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Book', verbose_name='книга')),
            ],
            options={
                'verbose_name': 'акция',
                'verbose_name_plural': 'акции',
            },
        ),
    ]
