# Generated by Django 2.2.1 on 2019-06-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0013_bookaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pk'], 'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
    ]
