# Generated by Django 2.2 on 2019-04-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionsapp', '0004_auto_20190405_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
    ]
