# Generated by Django 2.2 on 2019-04-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionsapp', '0006_agerestriction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agerestriction',
            options={'ordering': [], 'verbose_name': 'возрастное ограничение', 'verbose_name_plural': 'возрастные ограничения'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'автор', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='binding',
            options={'ordering': ['name'], 'verbose_name': 'переплет', 'verbose_name_plural': 'переплеты'},
        ),
        migrations.AlterModelOptions(
            name='formatbook',
            options={'ordering': ['name'], 'verbose_name': 'формат', 'verbose_name_plural': 'форматы'},
        ),
        migrations.AlterModelOptions(
            name='jenre',
            options={'ordering': ['name'], 'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='publishinghouse',
            options={'ordering': ['name'], 'verbose_name': 'издательство', 'verbose_name_plural': 'издательства'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['name'], 'verbose_name': 'серия', 'verbose_name_plural': 'серии'},
        ),
    ]
