# Generated by Django 2.2 on 2019-05-02 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionsapp', '0008_auto_20190412_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agerestriction',
            options={'ordering': ['description'], 'verbose_name': 'возрастное ограничение', 'verbose_name_plural': 'возрастные ограничения'},
        ),
    ]
