# Generated by Django 2.2.1 on 2019-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionsapp', '0010_auto_20190505_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='namePublic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя (для покупателя)'),
        ),
    ]
