# Generated by Django 2.2.1 on 2019-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionsapp', '0012_auto_20190509_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='namePublic',
            field=models.CharField(max_length=100, verbose_name='Имя (для покупателя)'),
        ),
    ]
