# Generated by Django 2.2.1 on 2019-05-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionsapp', '0013_auto_20190509_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'статус заказа',
                'verbose_name_plural': 'статусы закакза',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
