# Generated by Django 2.2.1 on 2019-05-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimensionsapp', '0014_orderstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['name'], 'verbose_name': 'статус заказа', 'verbose_name_plural': 'статусы заказа'},
        ),
    ]
