# Generated by Django 2.2.1 on 2019-05-27 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='аватар')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('dop_info', models.TextField(verbose_name='дополнительная информация')),
                ('home_country', models.CharField(max_length=50, verbose_name='домашний адрес - страна')),
                ('home_city', models.CharField(max_length=50, verbose_name='домашний адрес - город')),
                ('home_index', models.CharField(max_length=15, verbose_name='домашний адрес - индекс')),
                ('home_adress1', models.TextField(verbose_name='домашний адрес - адрес1')),
                ('home_adress2', models.TextField(verbose_name='домашний адрес - адрес2')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'дополнительные параметры профиля',
                'verbose_name_plural': 'дополнительные параметры профиля',
            },
        ),
    ]
