# Generated by Django 2.2.1 on 2019-05-27 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190527_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended', related_query_name='extended', to=settings.AUTH_USER_MODEL),
        ),
    ]
