# Generated by Django 2.2.1 on 2019-05-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0012_delete_menu'),
        ('cartapp', '0003_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', related_query_name='book', to='goodsapp.Book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', related_query_name='cart', to='cartapp.Cart')),
            ],
            options={
                'verbose_name': 'книга в корзине',
                'verbose_name_plural': 'книги в корзине',
            },
        ),
        migrations.AddConstraint(
            model_name='bookincart',
            constraint=models.UniqueConstraint(fields=('cart', 'book'), name='unique_book_in_cart'),
        ),
    ]
