# Generated by Django 2.2.1 on 2019-05-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dimensionsapp', '0015_auto_20190516_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('delivery_adress', models.TextField(verbose_name='Адрес доставки')),
                ('comments', models.TextField(verbose_name='комментарий')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart', related_query_name='cart', to='dimensionsapp.OrderStatus', verbose_name='корзина')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', related_query_name='status', to='dimensionsapp.OrderStatus', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
