# Generated by Django 2.2.1 on 2019-05-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', related_query_name='order', to='cartapp.Cart', verbose_name='корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', related_query_name='order', to='dimensionsapp.OrderStatus', verbose_name='статус'),
        ),
    ]
