# Generated by Django 2.2.1 on 2019-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_auto_20190516_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='noname', max_length=50, verbose_name='имя'),
            preserve_default=False,
        ),
    ]
