# Generated by Django 2.2.1 on 2019-05-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_order_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('manager', 'is_manager')], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_adress',
            field=models.TextField(help_text='Пример: г. Минск, ул. Звездная, д. 1, кв. 7', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, help_text='Электронная почта: example@domain.com', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='Как к вам обращаться?', max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Телефон для связи: +375(29)000-00-00', max_length=15, verbose_name='телефон'),
        ),
    ]
