# Generated by Django 2.2.4 on 2019-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curratesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currates',
            name='day',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
    ]
